name: Gitflow Release Demo
run-name: ${{ github.run_number }} - Deploy for ${{ github.ref_name }}
on:
  workflow_dispatch:
  push:
    branches:    
      - main

jobs:
  deploy-to-dev:
    runs-on: windows-latest
    environment: dev
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ vars.DB_URL }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Deploy to Dev
      run: python program.py
      
    
